apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-binding
subjects:
- kind: User
  name: ashutosh
  apiGroup: rbac.authorization.k8s.io
- kind: serviceAccount
  name: noti-serviceaccount
  namespcae: team4-ns
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
