apiVersion: apps/v1
kind: Deployment
metadata:
  name: duniversity-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: duniversity-backend
  template:
    metadata:
      labels:
        app: duniversity-backend
    spec:
      nodeSelector:
        training: devops

      # affinity:
      #   # -------------------------
      #   # NODE AFFINITY
      #   # -------------------------
      #   nodeAffinity:
      #     # HARD rule (must match)
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: training
      #           operator: In
      #           values:
      #           - devops

      #     # SOFT rule (preference)
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 50
      #       preference:
      #         matchExpressions:
      #         - key: node-type
      #           operator: In
      #           values:
      #           - backend

      #   # -------------------------
      #   # POD AFFINITY
      #   # -------------------------
      #   podAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 30
      #       podAffinityTerm:
      #         labelSelector:
      #           matchLabels:
      #             app: frontend
      #         topologyKey: kubernetes.io/hostname

      #   # -------------------------
      #   # POD ANTI-AFFINITY
      #   # -------------------------
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       podAffinityTerm:
      #         labelSelector:
      #           matchLabels:
      #             app: duniversity-backend
      #         topologyKey: kubernetes.io/hostname

      tolerations:
      - key: "key1"
        operator: "Equal"
        value: "ashu"
        effect: "NoSchedule"
      containers:
      - name: duniversity-backend
        image: ashutosh4782/duniversity-college-portal-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
