apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: team4-ns
subjects:
- kind: User
  name: ashutosh
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: noti-serviceaccount
  namespace: team4-ns
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
